# Default configuration for Server2 module
# Override using environment variables with the upper-snake-case representation of each key.

rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.password=guest
queue.name=SkierServletPostQueue
redis.uri=redis://localhost:6379
